name: Deploy Nginx

on:
  push:
    paths:
      - 'nginx/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Copy nginx files to server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: mirainest.asuscomm.com
          username: zerone6
          key: ${{ secrets.DEPLOY_KEY }}
          source: "nginx/"
          target: "~/app/"
          overwrite: true
      
      - name: Deploy nginx
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: mirainest.asuscomm.com
          username: zerone6
          key: ${{ secrets.DEPLOY_KEY }}
          script: |
            cd ~/app/nginx
            docker compose down
            docker compose build --no-cache
            docker compose up -d
